In [1]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10, 10])
vector

In [ ]:
vector.ndim

In [ ]:
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

In [ ]:
matrix.ndim

In [ ]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify dtype with `dtype` parameter

In [ ]:
another_matrix.ndim

In [ ]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

In [ ]:
tensor.ndim

In [ ]:
# Creating tensors with `tf.Variable`
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

In [ ]:
changeable_tensor[0].assign = 7

In [ ]:
changeable_tensor

# Creating random tensors

In [ ]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3, 2))
# Are they equal?
random_1, random_2, random_1 == random_2

In [ ]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim

In [ ]:
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.set_seed(42) # global level seed
tf.random.shuffle(not_shuffled, seed=42) # operation level seed

# 設定了 Global Seed 之後，每次運行都會得到相同的結果

In [ ]:
tf.ones([10, 7])

In [ ]:
tf.zeros(shape=(3, 4))

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a numpy array between 1 and 25
numpy_A

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)

In [ ]:
A, B

In [ ]:
C = tf.constant(numpy_A, shape=(2, 3, 4))

In [ ]:
C

# Getting information from tensors
When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
2*3*4*5

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

In [ ]:
test_tesnor = tf.constant([1, 2, 3])
test_tesnor[:2]

# Indexing tensors
Tensors can be indexed just like Python lists.

In [ ]:
# Get the first two elements of each dimension
# 取得每一個軸度的前兩個元素
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Get the first element from each dimension from each index except for the final one
# 取得每一個軸度的第一個元素，除了最後一個軸度
rank_4_tensor[:1, :1, :1, :]

In [ ]:
rank_4_tensor[:1, :1, :4, :1]

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]

In [ ]:
rank_3_tensor

In [ ]:
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]

In [ ]:
rank_3_tensor

In [ ]:
# Alternative to tf.newaxis
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

# Manipulating tensors (tensor operations)
Basic operations
`+`, `-`, `*`, `/`

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10

In [ ]:
# Original tensor is unchanged
tensor

In [ ]:
# Multiplication also works
tensor * 10

In [ ]:
# Subtraction
tensor - 10

In [ ]:
# Division
tensor / 10

In [ ]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10) # or tf.math.multiply()
# GPU 加速

**Matrix multiplication in tensorflow**
In machine learning, matrix multiplication is one of the most common tensor operations.
There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:
1. The inner dimensions must match.
2. The resulting matrix has the shape of the outer dimensions.

In [ ]:
# Matrix multiplication in tensorflow
tf.matmul(tensor, tensor)

In [ ]:
tensor * tensor # element-wise multiplication

In [ ]:
# Matrix multiplication with python operator '@'
tensor @ tensor # matrix multiplication

In [ ]:
# Create a tensor (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

# Try to multiply them (3, 2) * (3, 2) -> Error
# X @ Y

📖**Resouce:** Info and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
tf.reshape(Y, shape=(2, 3))

In [ ]:
# Try to multiply them (3, 2) * (2, 3) -> (3, 3)
X @ tf.reshape(Y, shape=(2, 3))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

In [ ]:
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

In [ ]:
X

In [ ]:
tf.reshape(X, shape=(2, 3))

In [ ]:
# Can do the same with transpose
tf.transpose(X)

In [ ]:
# transpose flip the axises rather than shuffle the elements
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

**The dot product**
Matrix multiplication is also referred to as the dot product.
You can perform matrix multiplication using:
* `tf.matmul()`
*  `tf.tensordot()`
* `@`

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

In [ ]:
# Check the values of Y, reshaped Y and transposed Y
print("Normal Y:")
print(Y, "\n") # "\n" is for a new line

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, shape=(2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

In [ ]:
tf.matmul(X, tf.transpose(Y))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

General, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules.

# Changing the datatype of a tensor

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

In [ ]:
C = tf.constant([7, 10])
C.dtype

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

In [ ]:
# Change from float32 to int32
F = tf.cast(tf.constant([-7.7, -10]), dtype=tf.int32)
F, F.dtype

# Aggregating tensors

In [ ]:
# Get the absolute values
D = tf.constant([-7, 10])
D, tf.abs(D)

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

In [ ]:
tf.size(E), E.shape, E.ndim

In [ ]:
# Get the minimum
tf.reduce_min(E)

In [ ]:
# Get the maximum
tf.reduce_max(E)

In [ ]:
# Get the mean
tf.reduce_mean(E)

In [ ]:
# Find the sum
tf.reduce_sum(E)

In [ ]:
# Find the variance
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

In [ ]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

# Find the positional maximum and minimum

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42) # set the random seed
F = tf.random.uniform(shape=[50])
F

In [ ]:
# Find the positional maximum
tf.argmax(F)

In [ ]:
# Index on out largest value position
F[tf.argmax(F)]

In [ ]:
# Find the positional minimum
tf.argmin(F)

In [ ]:
# Index on out smallest value position
F[tf.argmin(F)]

# Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42) # set the random seed
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

In [ ]:
G.shape, G.ndim

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape, G_squeezed.ndim

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be variable length

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="I love deep learning", off_value="I love TensorFlow")

# Squaring, log, square root

In [ ]:
# Create a new tensor
H = tf.range(1, 10)
H

In [ ]:
# Square our tensor
tf.square(H)

In [ ]:
tf.sqrt(tf.cast(H, dtype=tf.float16))

In [ ]:
# Find the log of our tensor
tf.math.log(tf.cast(H, dtype=tf.float16))

# Tensors and NumPy
TensorFlow interacts beautifully with NumPy arrays.

In [ ]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

In [ ]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

In [ ]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

In [ ]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype # numpy array is float64, tensor is float32

In [90]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [89]:
# Square our tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [91]:
tf.sqrt(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [94]:
# Find the log of our tensor
tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

# Tensors and NumPy
TensorFlow interacts beautifully with NumPy arrays.

In [96]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [97]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [98]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [99]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype # numpy array is float64, tensor is float32

(tf.float64, tf.float32)